name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "screenshotbot-test-project" #Must be unique in Heroku
          heroku_email: "thuvarahan.17@cse.mrt.ac.lk"
          remote_branch: "main"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test